// One sample of every od-kit component, for the gallery (kit/gallery.ts) and the coverage test.
// The same markup is what the prompt will show the model (KIT-04), so it is written the way a
// screen should use the kit.

export const KIT_SAMPLES: { name: string; html: string }[] = [
  { name: 'Page (the screen body: padding and section rhythm)', html: `<div class="od-page" style="padding:0"><div class="od-card od-card--flat">First section</div><div class="od-card od-card--flat">Second section</div></div>` },
  { name: 'Hero', html: `<div><div class="od-hero__eyebrow">Tuesday, 14 May</div><h1 class="od-hero__title">Good morning, Aziz</h1><p class="od-hero__sub">3 habits left for today</p></div>` },
  { name: 'Section header', html: `<div class="od-section"><div class="od-section__head"><h2 class="od-section__title">Recent</h2><button class="od-section__link">See all</button></div></div>` },
  { name: 'Buttons', html: `<div class="od-stack"><button class="od-btn od-btn--block">Continue</button><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="od-btn od-btn--secondary">Secondary</button><button class="od-btn od-btn--ghost">Ghost</button><button class="od-btn od-btn--sm">Small</button><button class="od-btn od-btn--danger od-btn--sm">Delete</button><button class="od-icon-btn" aria-label="Share"><i data-lucide="share-2"></i></button></div></div>` },
  { name: 'Card', html: `<div class="od-grid"><div class="od-card"><div class="od-stat"><span class="od-stat__label">Balance</span><span class="od-stat__value">$4,280</span><span class="od-stat__delta od-stat__delta--up">+2.4% this week</span></div></div><div class="od-card od-card--media"><div class="od-media od-media--wide"><img data-od-img="bowl of ramen" alt=""></div><div class="od-card__body"><p class="od-card__title">Tonkotsu Ramen</p><p class="od-card__meta">Menya · 25 min</p><span class="od-rating"><i data-lucide="star"></i>4.8</span></div></div></div>` },
  { name: 'List', html: `<div class="od-list"><a class="od-row od-row--chevron"><span class="od-row__lead"><i data-lucide="coffee"></i></span><span class="od-row__body"><span class="od-row__title">Blue Bottle</span><span class="od-row__sub">Today · Coffee</span></span><span class="od-row__trail">−$5.40</span></a><a class="od-row"><span class="od-row__lead"><i data-lucide="wallet"></i></span><span class="od-row__body"><span class="od-row__title">Salary</span><span class="od-row__sub">Mon · Income</span></span><span class="od-row__trail">+$3,200</span></a><div class="od-row"><span class="od-row__body"><span class="od-row__title">Notifications</span><span class="od-row__sub">Reminders and streaks</span></span><input type="checkbox" class="od-switch" role="switch" checked></div></div>` },
  { name: 'Chips, tags, badge, avatar', html: `<div class="od-stack"><div class="od-carousel"><button class="od-chip is-active">All</button><button class="od-chip">Pizza</button><button class="od-chip">Sushi</button><button class="od-chip">Burgers</button><button class="od-chip">Vegan</button></div><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span class="od-tag">New</span><span class="od-tag od-tag--success">Paid</span><span class="od-tag od-tag--warn">Pending</span><span class="od-tag od-tag--danger">Failed</span><span class="od-tag od-tag--neutral">Draft</span><span class="od-badge">3</span><span class="od-avatar od-avatar--sm">AK</span><span class="od-avatar">MR</span><span class="od-avatar od-avatar--lg">DL</span></div></div>` },
  { name: 'Inputs', html: `<div class="od-stack"><div class="od-search"><i data-lucide="search"></i><input placeholder="Search dishes"></div><label class="od-field"><span class="od-field__label">Email</span><input class="od-input" value="aziz@mail.uz"><span class="od-field__help">We send receipts here</span></label><label class="od-field od-field--error"><span class="od-field__label">Card number</span><input class="od-input" value="4242 42"><span class="od-field__help">Card number is too short</span></label><div class="od-segmented"><button class="is-active">Week</button><button>Month</button><button>Year</button></div><div style="display:flex;align-items:center;justify-content:space-between"><span class="od-price">$16.50 <span class="od-price__unit">/ each</span></span><span class="od-stepper"><button aria-label="Less">−</button><output>2</output><button aria-label="More">+</button></span></div></div>` },
  { name: 'Progress and totals', html: `<div class="od-card"><div class="od-progress" style="--value:68%"><span></span></div><div><div class="od-kv"><span>Subtotal</span><span>$33.00</span></div><div class="od-kv"><span>Delivery</span><span>$2.49</span></div><div class="od-kv od-kv--total"><span>Total</span><span>$35.49</span></div></div></div>` },
  { name: 'Timeline', html: `<div class="od-timeline"><div class="od-timeline__item is-done"><span class="od-timeline__dot"></span><div><b>Order placed</b><div class="od-row__sub">12:04</div></div></div><div class="od-timeline__item is-current"><span class="od-timeline__dot"></span><div><b>Courier on the way</b><div class="od-row__sub">ETA 12:31</div></div></div><div class="od-timeline__item"><span class="od-timeline__dot"></span><div><b>Delivered</b></div></div></div>` },
  { name: 'Banner, empty, divider', html: `<div class="od-stack"><div class="od-banner"><i data-lucide="info"></i><span>Free delivery on orders over $25.</span></div><div class="od-banner od-banner--warn"><i data-lucide="alert-triangle"></i><span>Your card expires next month.</span></div><hr class="od-divider"><div class="od-empty"><div class="od-empty__icon"><i data-lucide="inbox"></i></div><p class="od-empty__title">No orders yet</p><span>Your past orders will show up here.</span><button class="od-btn od-btn--sm">Browse restaurants</button></div></div>` },
  { name: 'Bottom bar', html: `<div class="od-bottom-bar" style="position:static"><span class="od-price">$35.49</span><button class="od-btn">Place order</button></div>` },
]
