#!/usr/bin/env python3
"""EMJ-01: rebuild runtime/emoji from Microsoft's Fluent Emoji (MIT).

  git clone --depth 1 --filter=blob:none --sparse https://github.com/microsoft/fluentui-emoji.git /tmp/fluent
  (cd /tmp/fluent && git sparse-checkout set --no-cone '/assets/*/metadata.json' '/assets/*/3D/*.png' '/assets/*/Default/3D/*.png')
  python3 scripts/fluent-emoji.py /tmp/fluent/assets

Writes runtime/emoji/<key>.webp (96px 3D stills), runtime/emoji/anim/<key>.webp (128px animated heroes, from
fluentui-emoji-animated, only the names in HEROES that exist there) and runtime/emoji-codes.js. A key is the
codepoints in hex joined by '-', without FE0F; a skin-tone emoji uses its default tone.
"""
import io, json, os, glob, sys, urllib.parse, urllib.request
from PIL import Image, ImageSequence

HEROES = ['Fire', 'Party popper', 'Star', 'Red heart', 'Rocket', 'Flexed biceps', 'Clapping hands', 'Raising hands', 'Droplet', 'Sun', 'Glowing star', 'Hundred points', 'Person in lotus position', 'Partying face', 'Smiling face with heart-eyes', 'Star-struck', 'Waving hand', 'Person running', 'Zzz', 'Sleeping face', 'Brain', 'Smiling face with smiling eyes', 'Thumbs up', 'Rainbow', 'Folded hands', 'Hugging face']
src, out = sys.argv[1], 'runtime/emoji'
os.makedirs(out + '/anim', exist_ok=True)
key_of = lambda d: '-'.join(c for c in json.load(open(os.path.join(src, d, 'metadata.json')))['unicode'].lower().split() if c != 'fe0f')
still, animated = [], []
for d in sorted(os.listdir(src)):
    if not os.path.exists(os.path.join(src, d, 'metadata.json')): continue
    pngs = glob.glob(os.path.join(src, d, '3D', '*.png')) or glob.glob(os.path.join(src, d, 'Default', '3D', '*.png'))
    if not pngs: continue
    Image.open(pngs[0]).convert('RGBA').resize((96, 96), Image.LANCZOS).save(f'{out}/{key_of(d)}.webp', 'WEBP', quality=82, method=6)
    still.append(key_of(d))
tree = json.load(urllib.request.urlopen('https://api.github.com/repos/microsoft/fluentui-emoji-animated/git/trees/main?recursive=1'))['tree']
files = [x['path'] for x in tree if x['path'].endswith('.png') and '/animated/' in x['path']]
for name in HEROES:
    c = [f for f in files if f.split('/')[1] == name]
    path = ([f for f in c if '/Default/' in f] or c or [None])[0]
    if not path or not os.path.exists(os.path.join(src, name, 'metadata.json')): continue
    im = Image.open(io.BytesIO(urllib.request.urlopen('https://media.githubusercontent.com/media/microsoft/fluentui-emoji-animated/main/' + urllib.parse.quote(path)).read()))
    frames, durs = [], []
    for i, f in enumerate(ImageSequence.Iterator(im)):
        if i % 2: continue  # every other frame: half the bytes, still smooth
        frames.append(f.convert('RGBA').resize((128, 128), Image.LANCZOS)); durs.append(f.info.get('duration', 33) * 2)
    frames[0].save(f'{out}/anim/{key_of(name)}.webp', 'WEBP', save_all=True, append_images=frames[1:], duration=durs, loop=0, quality=70, method=4)
    animated.append(key_of(name))
with open('runtime/emoji-codes.js', 'w') as f:
    f.write('// Generated by scripts/fluent-emoji.py — the Fluent Emoji (Microsoft, MIT) in runtime/emoji: 3D stills and animated heroes.\n// Keys are the codepoints in hex joined by "-", without FE0F.\n')
    f.write(f'export const STILL = new Set({json.dumps(sorted(still))})\nexport const ANIMATED = new Set({json.dumps(sorted(animated))})\n')
    f.write('// An export to one HTML file carries the images inline instead.\nexport const DATA = null\n')
print(len(still), 'stills,', len(animated), 'animated')
