// The exported app's entry: the app's screens on Konsta's <App>, with a stack navigator that plays the same
// push / pop / tab moves the studio's preview does. Generated by the studio's code export (CODE-01).
import { useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { App } from 'konsta/react'
import { AppContext } from './kit/nav.jsx'
import { applyStyle } from './kit/styles.js'
import { setupStore } from './kit/store.js'
import * as store from './store.js'
import app from './app.json'
import photos from './photos.json'
import { screens } from './screens/index.js'
import './styles.css'

/** A tab id or a screen id → the screen that shows it (a tab opens its root screen). */
const resolve = (id) => app.screens.find((s) => s.id === id) ?? app.screens.find((s) => s.kind === 'tab' && s.tab === id)
const first = app.screens.find((s) => s.kind === 'first-run') ?? app.screens.find((s) => s.kind === 'tab') ?? app.screens[0]
let uid = 0

function Navigator() {
  const [stack, setStack] = useState([{ id: first.id, params: {}, key: ++uid, anim: 'fade' }])
  const [leaving, setLeaving] = useState(null)
  const busy = useRef(false)
  const nav = {
    push: (id, params = {}) => resolve(id) && setStack((s) => [...s, { id: resolve(id).id, params, key: ++uid, anim: 'push' }]),
    pop: () => {
      if (busy.current) return
      setStack((s) => {
        if (s.length < 2) return s
        busy.current = true
        setLeaving(s[s.length - 1])
        setTimeout(() => {
          setLeaving(null)
          busy.current = false
        }, 340)
        return s.slice(0, -1)
      })
    },
    // A tab, or the end of onboarding: a new flow with nothing behind it.
    reset: (id) => resolve(id) && setStack([{ id: resolve(id).id, params: {}, key: ++uid, anim: 'fade' }]),
    current: null,
  }
  const draw = (r, cls) => {
    const Screen = screens[r.id]
    return (
      <div key={r.key} className={`vs-screen ${cls}`}>
        <AppContext value={{ tabs: app.tabs, screen: r.id, photos, nav: { ...nav, current: { name: r.id, params: r.params } } }}>
          <Screen {...r.params} />
        </AppContext>
      </div>
    )
  }
  return (
    <div className="vs-stack">
      {stack.map((r, i) => {
        const top = i === stack.length - 1
        if (i < stack.length - 2) return null // only the page underneath stays drawn
        return draw(r, top ? (r.anim === 'push' ? 'vs-top vs-push' : 'vs-top vs-fade') : 'vs-under')
      })}
      {leaving && draw(leaving, 'vs-pop')}
    </div>
  )
}

// FUN-01: one store for every screen, kept between visits.
setupStore(store, { id: app.name, persist: true })

const { dark, platform, style, accent } = app.theme
document.documentElement.classList.toggle('dark', dark)
// THM-01: the app's style — surfaces, corners and fonts — as on the canvas.
applyStyle(style, accent, dark)
createRoot(document.getElementById('root')).render(
  <App theme={platform === 'material' ? 'material' : 'ios'} dark={dark} safeAreas className={dark ? 'dark' : ''}>
    <Navigator />
  </App>,
)
