import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { frameSize } from './canvas'
import { cn } from '@/lib/utils'
import { themeMessage, withLiveTheme, type Theme } from '@/lib/theme-override'
import { parseHeightMessage, withHeightProbe } from '@/lib/frame-height'

// Renders at native device width; the height grows to fit the screen (see lib/frame-height.ts).
// The canvas's own transform handles zoom.
export function ScreenFrame(props: {
  html: string
  title: string
  device: string
  hint?: string
  selected?: boolean
  streaming?: boolean
  inspectMode?: boolean
  selectedElementId?: string | null
  onSelectElement?: (elementId: string, tag: string) => void
  theme?: Theme
  label?: ReactNode
  /** Identifies this frame in height messages; omit to keep the frame at the device height. */
  frameId?: string
  /** Last known content height, so the frame opens at the right size instead of jumping. */
  height?: number
  onHeight?: (frameId: string, height: number) => void
}) {
  const f = frameSize(props.device)
  const height = Math.max(f.height, props.height ?? f.height)
  // A new srcdoc reloads the iframe, so a streaming preview refreshes at most every 600ms
  const rawHtml = useThrottled(props.html, props.streaming ? 600 : 0)
  const isInteractive = props.inspectMode || props.selected
  const iframeRef = useRef<HTMLIFrameElement>(null)

  // The srcDoc carries the theme as it was when the HTML last changed. Later theme edits are
  // pushed into the running frame instead, so dragging a colour never reloads it.
  const themeRef = useRef(props.theme)
  themeRef.current = props.theme
  // A streaming frame is still half-written, so it measures nothing useful yet.
  const measuring = Boolean(props.frameId) && !props.streaming
  const themedHtml = useMemo(() => {
    if (!rawHtml) return rawHtml
    const themed = withLiveTheme(rawHtml, themeRef.current)
    return measuring ? withHeightProbe(themed, props.frameId!, f.height) : themed
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rawHtml, measuring, props.frameId, f.height])

  function pushTheme() {
    iframeRef.current?.contentWindow?.postMessage(themeMessage(themeRef.current), '*')
  }
  useEffect(pushTheme, [props.theme])

  // Element selection and frame height both arrive from the sandbox as postMessages.
  const onHeight = props.onHeight
  useEffect(() => {
    function handleMessage(e: MessageEvent) {
      // Every frame on the canvas listens on the same window. Without this check each of them
      // answered every frame's message, so picking an element in one screen selected another.
      if (e.source !== iframeRef.current?.contentWindow) return
      if (e.data && e.data.type === 'od:select_element') {
        props.onSelectElement?.(e.data.elementId, e.data.tag)
        return
      }
      const reported = onHeight ? parseHeightMessage(e.data, f.height) : null
      if (reported) onHeight!(reported.frameId, reported.height)
    }
    window.addEventListener('message', handleMessage)
    return () => window.removeEventListener('message', handleMessage)
  }, [props.onSelectElement, onHeight, f.height])

  // Preserve the FULL HTML document exactly as generated by the LLM
  // (contains its own head, styles, tokens, fonts, scripts)
  let finalHtml = themedHtml

  if (isInteractive && !props.streaming && rawHtml) {
    const selectedAttr = props.selectedElementId ? `[data-od-id="${props.selectedElementId}"]` : ''
    const bridgeScript = `
<style id="__od_interactive_bridge">
  [data-od-id] {
    cursor: pointer !important;
    transition: outline 0.12s ease !important;
  }
  [data-od-id]:hover {
    outline: 2px dashed #2563eb !important;
    outline-offset: 2px !important;
  }
  ${selectedAttr ? `
  ${selectedAttr} {
    outline: 2px solid #2563eb !important;
    outline-offset: 3px !important;
    box-shadow: 0 0 0 4px rgba(37,99,235,0.2) !important;
  }
  ` : ''}
</style>
<script id="__od_click_bridge">
  document.addEventListener('click', function(e) {
    var target = e.target.closest('[data-od-id]');
    if (!target) return;
    e.preventDefault();
    e.stopPropagation();
    var id = target.getAttribute('data-od-id');
    window.parent.postMessage({ type: 'od:select_element', elementId: id, tag: target.tagName.toLowerCase() }, '*');
  }, true);
</script>
`
    if (finalHtml.includes('</body>')) {
      finalHtml = finalHtml.replace('</body>', `${bridgeScript}</body>`)
    } else {
      finalHtml += bridgeScript
    }
  }

  return (
    <figure className="group relative" style={{ width: f.width }}>
      {props.label ?? (
        <figcaption
          className="mb-2 flex items-center gap-1.5 truncate text-sm font-medium text-muted-foreground"
          title={props.hint}
        >
          {props.streaming && <span className="size-2 shrink-0 animate-ping rounded-full bg-primary" />}
          {props.title}
        </figcaption>
      )}

      <div
        className={cn(
          'overflow-hidden rounded-xl border bg-white shadow-sm transition-all',
          props.selected ? 'border-primary ring-2 ring-primary/30' : 'border-border',
          props.streaming && 'ring-2 ring-primary/40'
        )}
        style={{ width: f.width, height }}
      >
        <iframe
          ref={iframeRef}
          onLoad={pushTheme}
          title={props.title}
          srcDoc={finalHtml}
          sandbox="allow-scripts"
          className={cn(
            'size-full',
            props.inspectMode ? 'pointer-events-auto' : 'pointer-events-none'
          )}
          style={{ width: f.width, height }}
        />
      </div>
    </figure>
  )
}

function useThrottled<T>(value: T, ms: number) {
  const [out, setOut] = useState(value)
  const last = useRef(0)
  useEffect(() => {
    if (ms <= 0) {
      setOut(value)
      return
    }
    const t = setTimeout(
      () => {
        last.current = Date.now()
        setOut(value)
      },
      Math.max(0, last.current + ms - Date.now()),
    )
    return () => clearTimeout(t)
  }, [value, ms])
  return out
}
